- name: gcr.io/cloud-builders/docker
  id: Builders
  args:[
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/airflow-data-pipeline',
      '--cache-from', 'gcr.io/$PROJECT_ID/airflow-data-pipeline:latest',
      './'
  ]